version: '3.1'

services:
  dotnet-worker:
    build:
      context: ../../testDotNetWorker/testWorker
      dockerfile: Dockerfile
    restart: always
    environment:
      WS_SITE: dotnet-webapp
      WS_PORT: 80
      DB_HOST: db
  dotnet-webapp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '9090:80'
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
  db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes: 
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: