version: '3.1'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
  db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes: 
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: